import _COLOR_CHART_ from "./images/COLOR_CHART.jpg";
import _DAY_INSIDE_BURGER_ from "./images/DAY_INSIDE_BURGER.jpg";
import _DAY_INSIDE_GROUP_ from "./images/DAY_INSIDE_GROUP.jpg";
import _DAY_INSIDE_RESTAURANT_ from "./images/DAY_INSIDE_RESTAURANT.jpg";
import _DAY_INSIDE_SHELF_ from "./images/DAY_INSIDE_SHELF.jpg";
import _DAY_INSIDE_RESTAURANT_02_ from "./images/DAY_INSIDE_RESTAURANT_02.jpg";
import _DAY_INSIDE_RESTAURANT_03_ from "./images/DAY_INSIDE_RESTAURANT_03.jpg";
import _DAY_INSIDE_RESTAURANT_PORTRAIT_ from "./images/DAY_INSIDE_RESTAURANT_PORTRAIT.jpg";
import _DAY_OUTSIDE_BRICKHOUSE_ from "./images/DAY_OUTSIDE_BRICKHOUSE.jpg";
import _DAY_OUTSIDE_PORTRAIT_ from "./images/DAY_OUTSIDE_PORTRAIT.jpg";
import _DAY_OUTSIDE_SKY_ROAD_ from "./images/DAY_OUTSIDE_SKY_ROAD.jpg";
import _IPHONE11_GRID_SAMPLES_01_ from "./images/IPHONE11_GRID_SAMPLES_01.jpg";
import _IPHONE11_NIGHT_CITY_ROAD_ from "./images/IPHONE11_NIGHT_CITY_ROAD.jpg";
import _IPHONE11_NIGHT_INSIDE_RESTAURANT_ from "./images/IPHONE11_NIGHT_INSIDE_RESTAURANT.jpg";
import _IPHONE11_NIGHT_OUTSIDE_BRIGHTLIGHT_ from "./images/IPHONE11_NIGHT_OUTSIDE_BRIGHTLIGHT.jpg";
import _IPHONE11_NIGHT_OUTSIDE_CITY_BUILDING_ from "./images/IPHONE11_NIGHT_OUTSIDE_CITY_BUILDING.jpg";
import _IPHONE11_NIGHT_OUTSIDE_CITY_BUS_ from "./images/IPHONE11_NIGHT_OUTSIDE_CITY_BUS.jpg";
import _IPHONE11_NIGHT_OUTSIDE_DARK_ from "./images/IPHONE11_NIGHT_OUTSIDE_DARK.jpg";
import _IPHONE11_NIGHT_OUTSIDE_DOCK_ from "./images/IPHONE11_NIGHT_OUTSIDE_DOCK.jpg";
import _IPHONE11_NIGHT_OUTSIDE_DOWNTOWN_ from "./images/IPHONE11_NIGHT_OUTSIDE_DOWNTOWN.jpg";
import _IPHONE11_NIGHT_OUTSIDE_FRONT_DOWNTOWN_ from "./images/IPHONE11_NIGHT_OUTSIDE_FRONT_DOWNTOWN.jpg";
import _IPHONE11_NIGHT_OUTSIDE_LOWLIGHT_ from "./images/IPHONE11_NIGHT_OUTSIDE_LOWLIGHT.jpg";
import _IPHONE11_NIGHT_OUTSIDE_NEON_LIGHTS_ from "./images/IPHONE11_NIGHT_OUTSIDE_NEON_LIGHTS.jpg";
import _IPHONE11_NIGHT_OUTSIDE_SOMELIGHT_ from "./images/IPHONE11_NIGHT_OUTSIDE_SOMELIGHT.jpg";
import _IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY1_ from "./images/IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY1.jpg";
import _IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY2_ from "./images/IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY2.jpg";
import _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE1_ from "./images/IPHONE11_NIGHT_OUTSIDE_CHERRYTREE1.jpg";
import _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE2_ from "./images/IPHONE11_NIGHT_OUTSIDE_CHERRYTREE2.jpg";
import _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE3_ from "./images/IPHONE11_NIGHT_OUTSIDE_CHERRYTREE3.jpg";
import _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE4_ from "./images/IPHONE11_NIGHT_OUTSIDE_CHERRYTREE4.jpg";
import _IPHONE11_NIGHT_OUTSIDE_REDFLOWER_ from "./images/IPHONE11_NIGHT_OUTSIDE_REDFLOWER.jpg";
import _IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR1_ from "./images/IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR1.jpg";
import _IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR2_ from "./images/IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR2.jpg";
import _IPHONE11_NIGHT_OUTSIDE_ROAD_PINETREE_ from "./images/IPHONE11_NIGHT_OUTSIDE_ROAD_PINETREE.jpg";
import _IPHONE11_NIGHT_OUTSIDE_YELLOWLIGHT_ from "./images/IPHONE11_NIGHT_OUTSIDE_YELLOWLIGHT.jpg";
import _IPHONEX_NIGHT_OUTSIDE_CITY_CROSSROAD_ from "./images/IPHONEX_NIGHT_OUTSIDE_CITY_CROSSROAD.jpg";
import _IPHONEX_NIGHT_OUTSIDE_CITY_BUILDING_ from "./images/IPHONEX_NIGHT_OUTSIDE_CITY_BUILDING.jpg";
import _IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN1_ from "./images/IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN1.jpg";
import _IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN2_ from "./images/IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN2.jpg";

const SampleImages = [
  { name: "COLOR_CHART", url: _COLOR_CHART_ },
  { name: "DAY_INSIDE_BURGER", url: _DAY_INSIDE_BURGER_ },
  { name: "DAY_INSIDE_GROUP", url: _DAY_INSIDE_GROUP_ },
  { name: "DAY_INSIDE_RESTAURANT", url: _DAY_INSIDE_RESTAURANT_ },
  { name: "DAY_INSIDE_RESTAURANT_02", url: _DAY_INSIDE_RESTAURANT_02_ },
  { name: "DAY_INSIDE_RESTAURANT_03", url: _DAY_INSIDE_RESTAURANT_03_ },
  {
    name: "DAY_INSIDE_RESTAURANT_PORTRAIT",
    url: _DAY_INSIDE_RESTAURANT_PORTRAIT_,
  },
  { name: "DAY_INSIDE_SHELF", url: _DAY_INSIDE_SHELF_ },
  { name: "DAY_OUTSIDE_BRICKHOUSE", url: _DAY_OUTSIDE_BRICKHOUSE_ },
  { name: "DAY_OUTSIDE_PORTRAIT", url: _DAY_OUTSIDE_PORTRAIT_ },
  { name: "DAY_OUTSIDE_SKY_ROAD", url: _DAY_OUTSIDE_SKY_ROAD_ },
  { name: "IPHONE11_GRID_SAMPLES_01", url: _IPHONE11_GRID_SAMPLES_01_ },
  { name: "IPHONE11_NIGHT_CITY_ROAD", url: _IPHONE11_NIGHT_CITY_ROAD_ },
  {
    name: "IPHONE11_NIGHT_INSIDE_RESTAURANT",
    url: _IPHONE11_NIGHT_INSIDE_RESTAURANT_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_BRIGHTLIGHT",
    url: _IPHONE11_NIGHT_OUTSIDE_BRIGHTLIGHT_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_CITY_BUILDING",
    url: _IPHONE11_NIGHT_OUTSIDE_CITY_BUILDING_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_CITY_BUS",
    url: _IPHONE11_NIGHT_OUTSIDE_CITY_BUS_,
  },
  { name: "IPHONE11_NIGHT_OUTSIDE_DARK", url: _IPHONE11_NIGHT_OUTSIDE_DARK_ },
  { name: "IPHONE11_NIGHT_OUTSIDE_DOCK", url: _IPHONE11_NIGHT_OUTSIDE_DOCK_ },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_DOWNTOWN",
    url: _IPHONE11_NIGHT_OUTSIDE_DOWNTOWN_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_FRONT_DOWNTOWN",
    url: _IPHONE11_NIGHT_OUTSIDE_FRONT_DOWNTOWN_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_LOWLIGHT",
    url: _IPHONE11_NIGHT_OUTSIDE_LOWLIGHT_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_NEON_LIGHTS",
    url: _IPHONE11_NIGHT_OUTSIDE_NEON_LIGHTS_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_SOMELIGHT",
    url: _IPHONE11_NIGHT_OUTSIDE_SOMELIGHT_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY1",
    url: _IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY1_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY2",
    url: _IPHONE11_NIGHT_OUTSIDE_BUILDING_SKY2_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_CHERRYTREE1",
    url: _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE1_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_CHERRYTREE2",
    url: _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE2_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_CHERRYTREE3",
    url: _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE3_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_CHERRYTREE4",
    url: _IPHONE11_NIGHT_OUTSIDE_CHERRYTREE4_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_REDFLOWER",
    url: _IPHONE11_NIGHT_OUTSIDE_REDFLOWER_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR1",
    url: _IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR1_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR2",
    url: _IPHONE11_NIGHT_OUTSIDE_ROAD_BLACKCAR2_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_ROAD_PINETREE",
    url: _IPHONE11_NIGHT_OUTSIDE_ROAD_PINETREE_,
  },
  {
    name: "IPHONE11_NIGHT_OUTSIDE_YELLOWLIGHT",
    url: _IPHONE11_NIGHT_OUTSIDE_YELLOWLIGHT_,
  },
  {
    name: "IPHONEX_NIGHT_OUTSIDE_CITY_CROSSROAD",
    url: _IPHONEX_NIGHT_OUTSIDE_CITY_CROSSROAD_,
  },
  {
    name: "IPHONEX_NIGHT_OUTSIDE_CITY_BUILDING",
    url: _IPHONEX_NIGHT_OUTSIDE_CITY_BUILDING_,
  },
  {
    name: "IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN1",
    url: _IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN1_,
  },
  {
    name: "IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN2",
    url: _IPHONE_XSMAX_NIGHT_OUTSIDE_DOWNTOWN2_,
  },
  { name: "----------", url: _COLOR_CHART_ },
];

export default SampleImages;
